pipeline {
    agent {
            kubernetes {
      yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    service_name: automate-services
    service_type: REST
spec:
  containers:
  - name: dnd
    image: docker:latest
    command: 
    - cat
    tty: true
    volumeMounts: 
    - mountPath: /var/run/docker.sock
      name: docker-sock
  - name: kubectl
    image: bryandollery/terraform-packer-aws-alpine
    command:
    - cat
    tty: true
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock  
      type: Socket
"""
    }
  }
    stages {

        stage ('build-elf') {
            steps { 
                container('kubectl') {
                    sh "rm -rf elf"
                    sh "git clone https://github.com/Danya-Mudaifea/elf"
                    sh "cd elf && ./elf.sh"
                    sh "curl localhost/elf"
                    sh "rm -rf elf"
                    sh "helm uninstall elasticsearch --namespace=elf"
                    sh "helm uninstall fluent-bit --namespace=elf"
                    sh "helm uninstall kibana --namespace=elf"
                    sh "kubectl delete random-logger -n elf"
                    sh "kubectl get all -n elf"
                }
            }
        }
    }
}